version: '3.8'
services: 
    db:
        image: mysql:5.7
        container_name: mysql
        volumes: 
            - db-data:/var/lib/mysql
        environment: 
            MYSQL_DATABASE: app_db
            MYSQL_USER: jokopwt
            MYSQL_PASSWORD: user
            MYSQL_ROOT_PASSWORD: root
        restart: always
        networks:
           - int-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports: 
            - '8080:80'
        restart: always
        depends_on: 
            - db
        networks: 
            - int-network

volumes: 
    db-data:

networks: 
    int-network: